# Generated by Django 5.0.7 on 2024-09-07 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=20)),
                ('user_password', models.CharField(max_length=128)),
                ('user_email', models.CharField(max_length=100, unique=True)),
                ('user_birth', models.DateField(blank=True, null=True)),
                ('user_avator', models.CharField(max_length=50)),
                ('user_age', models.IntegerField(blank=True, null=True)),
                ('last_update', models.DateTimeField()),
            ],
            options={
                'db_table': 'member',
                'managed': False,
            },
        ),
    ]
